# Theme Github link: https://github.com/korilin/hexo-theme-particle
# Developer: korilin

# html lang
language: zh

# avatar image url
head_img: images/1.png

# home page head info block
head_block_enable: true

# home page head background style.
# If you use a picture as background, you must use the css background-image attribute instead of the background attribute.
# Use image as background ==> home_background: "background-image:url('../home.jpg')"
# Use a color as background ==> home_background: "background: balck"
home_background: "background-image:url('home.jpg')"

# Particle theme icon is adopts the ant design vue icons
# Link：https://www.antdv.com/components/icon-cn/

# main menu navigation
menu:
  首页:
    icon:
      name: home
      theme: filled
    src: /
  项目:
    icon:
      name: folder
      theme: filled
    src: /项目
  B站:
    icon:
      name: youtube
      theme: filled
    src: http://localhost:5000/
  联系:
    icon:
      name: contacts
      theme: filled
    src: /联系
  归档:
    icon:
      name: folder
      theme: filled
    src: /archives
  分类:
    icon:
      name: book
      theme: filled
    src: /categories
  标签:
    icon:
      name: tags
      theme: filled
    src: /tags

# side info card
card:
  enable: true
  description: ["探索技术，追求卓越"]
  icon_links:
    github:
      icon:
        type: antd-icon
        name: github
        theme: filled
        src:
      link: https://github.com/wtyss
    twitter:
      icon:
        type: antd-icon
        name: twitter
        theme:
        src:
      link: https://twitter.com/wty
  friend_links:
    个人主页: /
    技术分享: /archives

# footer info
footer:
  since: 2018
  # Customize the server domain name ICP
  ICP:
    enable: true
    code: 暂未备案 

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
  enable: false
  clientID: # GitHub Application Client ID
  clientSecret: # GitHub Application Client Secret
  repo: hexo-theme-particle # The name of repository of store comments
  owner: korilin # GitHub repo owner
  admin: korilin # GitHub repo owner and collaborators, only these guys can initialize github issues
  language: en # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.

# theme style: full / night / maiden, defalut: full
style: maiden
